# Generated by Django 5.1.5 on 2025-01-20 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeeklyStats",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.BooleanField(default=True)),
                ("env", models.CharField(max_length=10)),
                ("week_start_date", models.CharField(max_length=20)),
                ("week_end_date", models.CharField(max_length=20)),
                ("counts", models.JSONField()),
                ("rates", models.JSONField()),
                ("labels", models.JSONField()),
            ],
            options={
                "verbose_name": "每周统计",
                "verbose_name_plural": "每周统计",
                "db_table": "weekly_stats",
            },
        ),
    ]
