# Generated by Django 5.1.5 on 2025-01-20 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.BooleanField(default=True)),
                ("env", models.CharField(max_length=10)),
                ("date", models.CharField(max_length=20)),
                ("counts", models.JSONField()),
                ("rates", models.JSONField()),
                ("labels", models.JSONField()),
            ],
            options={
                "verbose_name": "每日统计",
                "verbose_name_plural": "每日统计",
                "db_table": "daily_stats",
            },
        ),
    ]
